export const cardInfo = [
  {
    title: 'PLAN VIP',
    title_help: '(Plan Mensual)',
    subtitle: 'Incluye control cada 15 dias via ZOOM',
    old_price: 9500,
    new_price: 8100,
    old_price_uss: 120,
    new_price_uss: 99,
    price_group: false,
    items: [
      'Plan Personalizado de Entrenamiento',
      'Plan de Comidas',
      'Actualización cada 5 semanas',
      'Video demostrativo para cada ejercicio',
      'Seguimiento 24/7 vía Mail',
      'Acceso a plataforma',
      '*Suscripción requerida',
    ],
    button: 'ME SUMO!',
    payment_link: 'https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c938084745210b20174521aabd40002',
    payment_link_uss: 'https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-56K855191F542461TMQDVPPY',
    button_link: 'priceCheckout?name=vip',
    showInHome: true
  },
  {
    title: 'PLAN FULL',
    title_help: '(Plan Mensual)',
    subtitle: 'Incluye 1 sesion via zoom por mes',
    old_price: 7000,
    new_price: 6100,
    old_price_uss: 90,
    new_price_uss: 75,
    price_group: false,
    items: [
      'Plan Personalizado de Entrenamiento',
      'Plan de Comidas',
      'Actualización cada 5 semanas',
      'Video demostrativo para cada ejercicio',
      'Seguimiento 24/7 vía Mail',
      'Acceso a plataforma',
      '*Suscripción requerida',
    ],
    button: 'ME SUMO!',
    payment_link: 'https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c9380848573564c01857a7a32260576',
    payment_link_uss: 'https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-17139707J8887463SMQDVOJA',
    button_link: 'priceCheckout?name=full',
    showInHome: true
  },
  {
    title: 'COACHING ONLINE',
    title_help: '(Plan Mensual)',
    subtitle: '',
    subtitle_help: 'Incluye Plan de Comidas Personalizado',
    old_price: 7800,
    new_price: 6300,
    old_price_uss: 60,
    new_price_uss: 45,
    price_group: false,
    items: [
      'Plan Personalizado de Entrenamiento',
      'Plan de Comidas',
      'Actualización cada 5 semanas',
      'Video demostrativo para cada ejercicio',
      'Seguimiento 24/7 vía Mail',
      'Acceso a plataforma',
      '*Suscripción requerida',
    ],
    button: 'Empecemos!',
    payment_link: 'https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c93808486b533610186b8e7c4ca0217',
    payment_link_uss: 'https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-9AM94611HY5978411MQDVLCA',
    button_link: 'priceCheckout?name=coaching',
    showInHome: false
  },
  {
    title: 'COACHING ONLINE',
    title_help: '(Plan Mensual)',
    subtitle: '',
    subtitle_help: 'No incluye Plan de Comidas Personalizado',
    old_price: 4900,
    new_price: 4200,
    old_price_uss: 50,
    new_price_uss: 35,
    price_group: false,
    items: [
      'Plan Personalizado de Entrenamiento',
      'Plan de Comidas',
      'Actualización cada 5 semanas',
      'Video demostrativo para cada ejercicio',
      'Seguimiento 24/7 vía Mail',
      'Acceso a plataforma',
      '*Suscripción requerida',
    ],
    button: 'Empecemos!',
    payment_link: 'https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c9380848244949c01824577533b00af',
    payment_link_uss: 'https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-4XU11738SG080144CMQDVHVA',
    button_link: 'priceCheckout?name=coaching',
    showInHome: true
  }
]